global:
    domain: 'http://test.local'
    title: 'Default Title'
    description: 'Default Description'
    keywords: 'Default Keywords'
    template: 'example.html'
    #do not put spaces between file names
    javascript: 'test.js,test2.js,test3.js' 
    css: 'example.css'
    # to use compression, all files must be in the root js directory,  the js setting will not take / 
    compress_js: false 
    # to use compression, all files must be in the root js directory, the js setting will not take /
    compress_css: true 
    #Directory where compression file lives
    css_compress_directory: design/css/min/
    #Directory where compression file lives 
    js_compress_directory: design/js/min/
    enable_caching: true
    changefreq: 'weekly'
    priority: '1'
    script_key: '62189a5b79edff2b2708ede2683fa911'
'404':
    title: '404 Error'
    description: ''
    keywords: ''
    template: ''
    javascript: ''
    css:
    landing_page: false
    cache: true
'sitemap':
    title: ''
    description: ''
    keywords: ''
    template: 'sitemap.xml'
    javascript: ''
    css:
    landing_page: false
    cache: false
# /Required Parameters
'index':
    title: 'Page Title'
    description: 'Page Description'
    keywords: 'Page keywords'
    template: 'second_layout.html'
    javascript: ''
    css: ''
    landing_page: true
    cache: true
    changefreq: 'daily'
    priority: '2'
'example':
    title: 'Page Title'
    description: 'Page Description'
    keywords: 'Page keywords'
    template: ''
    javascript: ''
    css: ''
    landing_page: false
    cache: true
    changefreq: 'daily'
    priority: '2'
'example-directory/example':
    title: 'Page Title'
    description: 'Page Description'
    keywords: 'Page keywords'
    template: ''
    javascript: 'test.js,test2.js'
    css: 'example.css'
    landing_page: false
    cache: true
    changefreq: 'daily'
    priority: '2'